apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/source-location: url:https://${{ values.repoUrl.host }}/${{ values.repoUrl.owner }}/${{ values.repoUrl.repo }}
    github.com/project-slug: ${{ values.repoUrl.owner }}/${{ values.repoUrl.repo }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - react
    - vite  
    - frontend
    - typescript
    - ${{ values.uiLibrary }}
  labels:
    system: ${{ values.system }}
spec:
  type: website
  lifecycle: production
  owner: ${{ values.owner }}
  system: ${{ values.system }}
