apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: React frontend application
  annotations:
    github.com/project-slug: ${{ values.repoUrl.owner }}/${{ values.repoUrl.repo }}
  tags:
    - react
    - frontend
    - web
spec:
  type: website
  lifecycle: production
  owner: group:default/admin
