{% if values.deployToKubernetes %}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
    system: ${{ values.system }}
    component: frontend
spec:
  replicas: ${{ values.replicas }}
  selector:
    matchLabels:
      app: ${{ values.name }}
  template:
    metadata:
      labels:
        app: ${{ values.name }}
        system: ${{ values.system }}
        component: frontend
    spec:
      containers:
        - name: ${{ values.name }}
          image: ${{ values.name }}:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: VITE_API_URL
              value: "${{ values.apiUrl }}"
            - name: VITE_APP_NAME
              value: "${{ values.name }}"
            - name: VITE_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: registry-secret

---

apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}-service
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
    system: ${{ values.system }}
    component: frontend
spec:
  selector:
    app: ${{ values.name }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.name }}-ingress
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
    system: ${{ values.system }}
    component: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: ${{ values.name }}.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${{ values.name }}-service
                port:
                  number: 80
{% endif %}
